## 5.16 List 2 Dimensi

List 2 dimensi pada umumnya adalah menempatkan sebuah list di dalam list.
Penggambarannya seperti sebuah matrik.

#### Contoh Penerapan List 2 Dimensi

In [2]:
matrik = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
print (matrik)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [3]:
matrik[0]

[1, 2, 3, 4]

In [4]:
matrik [1][2]
# diitung dari 0
# ini maksudnya baris kedua, kolom ke tiga
# ke kanan kolom, kebawah baris

7

In [6]:
matrik[3][2]

15

In [7]:
matrik[2][3] = 50
print (matrik[2][3])

50


In [8]:
matrik
# hasil yang muncul dalah yang sudah diperbarui

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 50], [13, 14, 15, 16]]

#### Cara memanggil anggota dari list 2 dimensi

In [9]:
for baris in matrik:
    print(baris)
    for kolom in baris:
        print (kolom)

[1, 2, 3, 4]
1
2
3
4
[5, 6, 7, 8]
5
6
7
8
[9, 10, 11, 50]
9
10
11
50
[13, 14, 15, 16]
13
14
15
16


## 5.17 Tuples

Tuples mirip dengan list, akan tetapi tuples tidak dapat dirubah isinya. Jika kita
memiliki data yang tidak ingin dirubah isinya, kita gunakan tuples, sedangkan
jika datanya masih ingin dimanipulasi kedepannya, gunakan list.

In [12]:
angka = (0,1,1,3,4,5)

In [13]:
print (angka[0])

0


In [14]:
print (angka[0:4])

(0, 1, 1, 3)


In [15]:
for isi in angka[0:4]:
    print (isi)

0
1
1
3


In [16]:
angka[1] = 8
# karena tuples tidak dapat diganti isinya

TypeError: 'tuple' object does not support item assignment

In [17]:
angka.append(4)
# tidak bisa menambahkan

AttributeError: 'tuple' object has no attribute 'append'

In [18]:
angka.remove(0)
# tidak bisa diganti

AttributeError: 'tuple' object has no attribute 'remove'

In [19]:
angka.count(5)
# jumlah angkanya, misal 5 ada 1

1

In [21]:
angka.count(1)
# jumlah angkanya, banyaknya angka 1 ada 2

2

In [20]:
angka.index(4)

4

In [26]:
angka.index(2)
# eror, karena angka 2 tidak ada di dalam isi angka

ValueError: tuple.index(x): x not in tuple

## 5.18 Dictionaries

Dictionaries digunakan jika data nya terkait satu sama lain. Misalnya data
seseorang yang terdiri dari umur, nama, tanggal lahir merupakan satu kesatuan
data yang bersumber dari orang tersebut.

In [30]:
data_orang = {
    "nama" : "Nyoman Paul",
    "umur" : 22, 
    "apakah_single" : False

SyntaxError: unexpected EOF while parsing (1343803681.py, line 4)

In [31]:
print (data_orang["nama"])

Nyoman Paul


In [32]:
print (data_orang['Nama'])
# eror karena variabel yang dimasukan nama bukan Nama
# huruf besar dan kecil sangat mempengaruhi

KeyError: 'Nama'

In [33]:
print (data_orang.get("nama"))

Nyoman Paul


In [34]:
print (data_orang.get("Nama"))

None


In [35]:
print (data_orang.get("tanggal lahir"))
# karena tidak ada memasukan tanggal lahir

None


In [36]:
print(data_orang.get("tanggal_lahir", "16 Juni 2001"))

16 Juni 2001


In [37]:
print (data_orang)

{'nama': 'Nyoman Paul', 'umur': 22, 'apakah_single': False}


In [38]:
print(data_orang["tanggal_lahir"])

KeyError: 'tanggal_lahir'

In [41]:
data_orang["HP"] = '08123456789'

In [42]:
print (data_orang["HP"])

08123456789


In [43]:
print (data_orang)

{'nama': 'Nyoman Paul', 'umur': 22, 'apakah_single': False, 'HP': '08123456789'}


## 5.19 Fungsi dalam Python

Sampai sejauh ini tanpa disadari kita telah menerapkan beberapa jenis fungsi
pada Python seperti fungsi input, print, len, range, dll. Pada dasarnya fungsi
dibentuk untuk menghidari pengulangan pembuatan program secara manual
dimana fungsi tersebut memiliki pengulangan yang tinggi dalam program yang
kita buat. Jadi untuk mempermudah dan meringkas program yang kita buat,
setiap fungsi tersebut dibutuhkan tinggal kita panggil.

#### Contoh fungsi dalam Python

In [50]:
def full_name(first_name,last_name) :
    print (f"Nama lengkapnya adalah {first_name} {last_name}")

In [51]:
first_name = input("Nama depan anda adalah ")
last_name = input("Nama belakang anda adalah ")
full_name(first_name,last_name)

Nama depan anda adalah Nyoman
Nama belakang anda adalah Paul
Nama lengkapnya adalah Nyoman Paul


### 5.19.1 Tugas Fungsi pada Python

Ada dua jenis tugas fungsi pada Python yaitu:
1. Menjalankan perintah.
2. Menampilkan hasil perhitungan.

In [52]:
def waktu_sampai(jarak,kecepatan):
    waktu = jarak/kecepatan
    print(waktu)

In [53]:
def waktu_tempuh(jarak,kecepatan) :
    waktu = jarak/kecepatan
    return waktu

In [54]:
waktu_sampai(80,60)

1.3333333333333333


In [55]:
waktu_tempuh(80,60)

1.3333333333333333

In [67]:
a = waktu_sampai(80,60)
print (a)

1.3333333333333333
None


In [68]:
b = waktu_tempuh(80,60)
print (b)

1.3333333333333333


##  5.20 Numpy

In [1]:
import pandas as pd

In [2]:
import numpy

### 5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy

In [5]:
a = numpy.array([0,1,2,3,4])
print (a)

[0 1 2 3 4]


In [7]:
b = numpy.array([[5,6,7,8],[9,8,7,6]])
print(b)

[[5 6 7 8]
 [9 8 7 6]]


In [69]:
c = nump.array([[[0,1,2,3],[4,5,6,7]],[[8,9,8,7],[6,5,4,3]],[[1,2,3,4],[5,6,7,8]]])
print(c)

NameError: name 'np' is not defined

In [ ]:
tugas sampai numpy